[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["antoine de jomini <gamedesignwargame@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
black = "^22.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
